"""Allowlist of runnable profiles for the remote runner.

A request (remote/request.json) may only NAME a profile defined here and supply
parameters validated against that profile's schema. No request field is ever
executed as a shell string: the runner builds an argv list from the profile.

To add an experiment: add a PROFILES entry (entry script inside the repo, fixed args,
optional validated params, timeout, declared inputs and output globs) and commit a new
remote/request.json that selects it. See remote/README.md.
"""

# Every profile runs as:  <venv python> <entry> <args...>   (no shell)
PROFILES = {
    "e6nv_runner_engine_evidence_scope": {
        "description": "Engine-free scope metadata checks; does not repeat any physical calculation.",
        "entry": "docs/audits/2026-10-10-e6nv-runner-engine-evidence-scope/run_checks.py",
        "args": [], "params": {}, "timeout_s": 150, "engine_info": False,
        "inputs": ["remote/run_profile.py", "remote/README.md",
                   "docs/audits/2026-10-10-e6nv-runner-engine-evidence-scope/CHECKS.md",
                   "docs/audits/2026-10-10-e6nv-runner-engine-evidence-scope/run_checks.py",
                   "tests/unit/test_remote_engine_evidence_scope_mock.py",
                   "tests/unit/test_measurement_requested_bias_mock.py", "tests/unit/test_node_field_caption_mock.py",
                   "tcad_2d_stagewise.py", "tcad/characterization/interface.py", "tcad/characterization/node_fields.py"],
        "outputs": [{"glob": "e6nv_out/**/*", "max_mb": 2}],
        "regenerate": "Three pure contract tests; no engine import and no physical solve.",
    },
    "e6nu_carrier_compensation_boundary": {
        "description": "Four actual p/n uniform numeric GUI controls plus eight preserved compensated transport refusals.",
        "entry": "docs/audits/2026-10-10-e6nu-carrier-compensation-order/run_boundary.py",
        "args": [], "params": {}, "timeout_s": 500, "engine_info": False,
        "inputs": ["tcad_2d_stagewise.py", "tcad/characterization/node_fields.py",
                   "tcad/characterization/interface.py", "tcad/characterization/source_context.py",
                   "tcad/characterization/pn_junction_iv_sweep.py", "tcad/physics/doping.py",
                   "tcad/physics/wafer_state_accumulation.py", "tcad/physics/wafer_state_v2.py",
                   "tcad/device/devsim/doping_mapping.py",
                   "docs/audits/2026-10-10-e6nu-carrier-compensation-order/PLAN_BOUNDARY.md",
                   "docs/audits/2026-10-10-e6nu-carrier-compensation-order/check_boundary.py",
                   "docs/audits/2026-10-10-e6nu-carrier-compensation-order/judge.py",
                   "docs/audits/2026-10-10-e6nu-carrier-compensation-order/judge_boundary.py",
                   "docs/audits/2026-10-10-e6nu-carrier-compensation-order/test_contract.py",
                   "docs/audits/2026-10-10-e6nu-carrier-compensation-order/test_boundary.py",
                   "docs/audits/2026-10-10-e6nu-carrier-compensation-order/run_boundary.py",
                   "docs/audits/2026-10-01-batch7h-e6i-uniform-resistor-dd/scripts/resistor_judge.py",
                   "tests/integration/test_uniform_resistor_dd_current_real.py",
                   "tests/unit/test_measurement_requested_bias_mock.py", "tests/unit/test_node_field_caption_mock.py",
                   "tests/unit/test_wafer_state_v2_fail_closed_no_resurrection_mock.py"],
        "outputs": [{"glob": "e6nu_boundary_out/**/*", "max_mb": 12}],
        "regenerate": "12 actual solves for four single-polarity controls; compensated transport remains refused, no gate removal.",
    },
    "e6nu_carrier_compensation_order": {
        "description": "Twelve actual uniform ACTIVE GUI requests: p/n majority and compensated declarations in both orders.",
        "entry": "docs/audits/2026-10-10-e6nu-carrier-compensation-order/run_checks.py",
        "args": [], "params": {}, "timeout_s": 500, "engine_info": False,
        "inputs": ["tcad_2d_stagewise.py", "tcad/characterization/node_fields.py",
                   "tcad/characterization/interface.py", "tcad/characterization/source_context.py",
                   "tcad/characterization/pn_junction_iv_sweep.py", "tcad/physics/doping.py",
                   "tcad/physics/wafer_state_accumulation.py", "tcad/physics/wafer_state_v2.py",
                   "tcad/device/devsim/doping_mapping.py",
                   "docs/audits/2026-10-10-e6nu-carrier-compensation-order/PLAN.md",
                   "docs/audits/2026-10-10-e6nu-carrier-compensation-order/check_matrix.py",
                   "docs/audits/2026-10-10-e6nu-carrier-compensation-order/judge.py",
                   "docs/audits/2026-10-10-e6nu-carrier-compensation-order/test_contract.py",
                   "docs/audits/2026-10-10-e6nu-carrier-compensation-order/run_checks.py",
                   "docs/audits/2026-10-01-batch7h-e6i-uniform-resistor-dd/scripts/resistor_judge.py",
                   "tests/integration/test_uniform_resistor_dd_current_real.py",
                   "tests/unit/test_measurement_requested_bias_mock.py", "tests/unit/test_node_field_caption_mock.py",
                   "tests/unit/test_wafer_state_v2_fail_closed_no_resurrection_mock.py"],
        "outputs": [{"glob": "e6nu_out/**/*", "max_mb": 12}],
        "regenerate": "36 actual constant-mobility uniform resistor solves; ACTIVE declarations, not implantation or activation simulation.",
    },
    "e6nt_uniform_gui_bias_axis": {
        "description": "Eight actual supported uniform Si GUI requests: polarity, zero, source swap, x/y axis; existing analytic criteria.",
        "entry": "docs/audits/2026-10-10-e6nt-uniform-gui-bias-axis/run_checks.py",
        "args": [], "params": {}, "timeout_s": 400, "engine_info": False,
        "inputs": ["tcad_2d_stagewise.py", "tcad/characterization/node_fields.py",
                   "tcad/characterization/interface.py", "tcad/characterization/source_context.py",
                   "tcad/characterization/pn_junction_iv_sweep.py",
                   "docs/audits/2026-10-10-e6nt-uniform-gui-bias-axis/PLAN.md",
                   "docs/audits/2026-10-10-e6nt-uniform-gui-bias-axis/check_matrix.py",
                   "docs/audits/2026-10-10-e6nt-uniform-gui-bias-axis/judge.py",
                   "docs/audits/2026-10-10-e6nt-uniform-gui-bias-axis/test_contract.py",
                   "docs/audits/2026-10-10-e6nt-uniform-gui-bias-axis/run_checks.py",
                   "docs/audits/2026-10-01-batch7h-e6i-uniform-resistor-dd/scripts/resistor_judge.py",
                   "tests/integration/test_uniform_resistor_dd_current_real.py",
                   "tests/unit/test_measurement_requested_bias_mock.py", "tests/unit/test_node_field_caption_mock.py",
                   "tests/unit/test_node_field_contacts_mock.py"],
        "outputs": [{"glob": "e6nt_out/**/*", "max_mb": 8}],
        "regenerate": "24 actual low-field uniform resistor solves only; no PN/oxide/MOS capability approval.",
    },
    "e6ns_requested_bias_evidence": {
        "description": "Requested terminal voltage/result identity boundary, controlled metadata faults after actual solves.",
        "entry": "docs/audits/2026-10-10-e6ns-requested-bias-evidence/run_checks.py",
        "args": [], "params": {}, "timeout_s": 400, "engine_info": False,
        "inputs": ["tcad_2d_stagewise.py", "tcad/characterization/interface.py",
                   "tcad/characterization/node_fields.py", "tcad/characterization/source_context.py",
                   "tcad/characterization/pn_junction_iv_sweep.py", "tcad/characterization/robust_iv_sweep.py",
                   "docs/audits/2026-10-10-e6ns-requested-bias-evidence/PLAN.md",
                   "docs/audits/2026-10-10-e6ns-requested-bias-evidence/run_checks.py",
                   "docs/audits/2026-10-10-e6ns-requested-bias-evidence/check_gui.py",
                   "tests/unit/test_measurement_requested_bias_mock.py", "tests/unit/test_measurement_validity_mock.py",
                   "tests/unit/test_node_field_caption_mock.py", "tests/unit/test_node_field_contacts_mock.py",
                   "tests/unit/test_node_field_export_mock.py", "tests/unit/test_node_field_hover_mock.py",
                   "tests/unit/test_node_fields_mock.py", "tests/unit/test_field_readout_invalidation_mock.py",
                   "tests/integration/test_uniform_resistor_dd_current_real.py"],
        "outputs": [{"glob": "e6ns_out/**/*", "max_mb": 8}],
        "regenerate": "Same supported uniform DD; injected record corruption is not an observed engine failure.",
    },
    "e6nr_field_physical_caption": {
        "description": "Actual field region/contact bias and raw Potential convention; no equations or gate changes.",
        "entry": "docs/audits/2026-10-10-e6nr-field-physical-caption/run_checks.py",
        "args": [], "params": {}, "timeout_s": 400, "engine_info": False,
        "inputs": ["tcad_2d_stagewise.py", "tcad/characterization/node_fields.py",
                   "tcad/characterization/interface.py", "tcad/characterization/source_context.py",
                   "docs/audits/2026-10-10-e6nr-field-physical-caption/PLAN.md",
                   "docs/audits/2026-10-10-e6nr-field-physical-caption/run_checks.py",
                   "docs/audits/2026-10-10-e6nr-field-physical-caption/check_gui.py",
                   "tests/unit/test_node_field_caption_mock.py", "tests/unit/test_node_field_contacts_mock.py",
                   "tests/unit/test_node_field_export_mock.py", "tests/unit/test_node_field_hover_mock.py",
                   "tests/unit/test_node_fields_mock.py", "tests/unit/test_field_readout_invalidation_mock.py",
                   "tests/integration/test_gui_current_unit_contract_real.py",
                   "tests/integration/test_uniform_resistor_dd_current_real.py"],
        "outputs": [{"glob": "e6nr_out/**/*", "max_mb": 8}],
        "regenerate": "Actual unchanged uniform DD fields with physically explicit captions; no PN approval.",
    },
    "e6nq_field_contact_evidence": {
        "description": "Complete two-terminal field export evidence; physical models and gates unchanged.",
        "entry": "docs/audits/2026-10-10-e6nq-field-contact-evidence/run_checks.py",
        "args": [], "params": {}, "timeout_s": 350, "engine_info": False,
        "inputs": ["tcad_2d_stagewise.py", "tcad/characterization/node_fields.py",
                   "tcad/characterization/interface.py", "tcad/characterization/source_context.py",
                   "docs/audits/2026-10-10-e6nq-field-contact-evidence/PLAN.md",
                   "docs/audits/2026-10-10-e6nq-field-contact-evidence/run_checks.py",
                   "docs/audits/2026-10-07-e6no-field-export/check_gui.py",
                   "tests/unit/test_node_field_contacts_mock.py", "tests/unit/test_node_field_export_mock.py",
                   "tests/unit/test_node_field_hover_mock.py", "tests/unit/test_node_fields_mock.py",
                   "tests/unit/test_field_readout_invalidation_mock.py",
                   "tests/integration/test_gui_current_unit_contract_real.py",
                   "tests/integration/test_uniform_resistor_dd_current_real.py"],
        "outputs": [{"glob": "e6no_out/**/*", "max_mb": 8}],
        "regenerate": "Existing actual uniform DD GUI export plus complete contact evidence controls, not PN approval.",
    },
    "e6no_field_export": {
        "description": "Actual node arrays with single-bias units/source JSON; no model or gate change.",
        "entry": "docs/audits/2026-10-07-e6no-field-export/run_checks.py",
        "args": [], "params": {}, "timeout_s": 350, "engine_info": False,
        "inputs": ["tcad_2d_stagewise.py", "tcad/characterization/node_fields.py", "tcad/characterization/source_context.py",
                   "docs/audits/2026-10-07-e6no-field-export/PLAN.md", "docs/audits/2026-10-07-e6no-field-export/check_gui.py",
                   "docs/audits/2026-10-07-e6no-field-export/run_checks.py", "tests/unit/test_node_field_export_mock.py",
                   "tests/unit/test_node_field_hover_mock.py", "tests/unit/test_node_fields_mock.py",
                   "docs/audits/2026-10-07-e6np-readout-invalidation/PLAN.md", "tests/unit/test_field_readout_invalidation_mock.py",
                   "tests/integration/test_gui_current_unit_contract_real.py", "tests/integration/test_uniform_resistor_dd_current_real.py"],
        "outputs": [{"glob": "e6no_out/**/*", "max_mb": 8}],
        "regenerate": "Actual supported uniform DD field export, not generic TCAD validation.",
    },
    "e6nn_field_hover": {
        "description": "Exact displayed-node hover and reset; physical equations and gates unchanged.",
        "entry": "docs/audits/2026-10-07-e6nn-field-hover/run_checks.py",
        "args": [], "params": {}, "timeout_s": 350, "engine_info": False,
        "inputs": ["tcad_2d_stagewise.py", "tcad/characterization/node_fields.py", "tcad/characterization/source_context.py",
                   "docs/audits/2026-10-07-e6nn-field-hover/PLAN.md",
                   "docs/audits/2026-10-07-e6nn-field-hover/check_gui.py", "docs/audits/2026-10-07-e6nn-field-hover/run_checks.py",
                   "tests/unit/test_node_field_hover_mock.py", "tests/unit/test_node_fields_mock.py",
                   "tests/integration/test_gui_current_unit_contract_real.py", "tests/integration/test_uniform_resistor_dd_current_real.py"],
        "outputs": [{"glob": "e6nn_out/**/*", "max_mb": 8}],
        "regenerate": "Actual uniform DD node hover; no PN or MOSFET approval.",
    },
    "e6nm_node_fields": {
        "description": "Preserve actual supported measurement node fields and display all-node samples; gates unchanged.",
        "entry": "docs/audits/2026-10-07-e6nm-node-fields/run_checks.py",
        "args": [], "params": {}, "timeout_s": 350, "engine_info": False,
        "inputs": ["tcad_2d_stagewise.py", "tcad/characterization/node_fields.py", "tcad/characterization/source_context.py",
                   "docs/audits/2026-10-07-e6nm-node-fields/PLAN.md",
                   "docs/audits/2026-10-07-e6nm-node-fields/check_gui.py",
                   "docs/audits/2026-10-07-e6nm-node-fields/run_checks.py",
                   "tests/unit/test_node_fields_mock.py", "tests/integration/test_gui_current_unit_contract_real.py",
                   "tests/integration/test_uniform_resistor_dd_current_real.py"],
        "outputs": [{"glob": "e6nm_out/**/*", "max_mb": 8}],
        "regenerate": "Actual uniform DD field snapshot and Tk node-sample map, not general PN approval.",
    },
    "e6nl_export_evidence": {
        "description": "DC unit metadata and CSV companion evidence; no physical model changes.",
        "entry": "docs/audits/2026-10-07-e6nl-export-evidence/run_checks.py",
        "args": [], "params": {}, "timeout_s": 320, "engine_info": False,
        "inputs": ["tcad_2d_stagewise.py", "tcad/characterization/io.py", "tcad/characterization/source_context.py",
                   "docs/audits/2026-10-07-e6nl-export-evidence/PLAN.md",
                   "docs/audits/2026-10-07-e6nl-export-evidence/check_gui.py",
                   "docs/audits/2026-10-07-e6nl-export-evidence/run_checks.py",
                   "tests/unit/test_measurement_export_evidence_mock.py",
                   "tests/unit/test_measurement_entry_point_gate_mock.py"],
        "outputs": [{"glob": "e6nl_out/**/*", "max_mb": 8}],
        "regenerate": "GUI mock DC export wiring and actual existing uniform DD current control; no MOSFET approval.",
    },
    "e6nk_electrode_context": {
        "description": "Bind resolved devices and exported DC results to current mesh/state/pins; gates unchanged.",
        "entry": "docs/audits/2026-10-07-e6nk-electrode-source-context/run_checks.py",
        "args": [], "params": {}, "timeout_s": 350, "engine_info": False,
        "inputs": ["tcad_2d_stagewise.py", "tcad/characterization/source_context.py",
                   "docs/audits/2026-10-07-e6nk-electrode-source-context/PLAN.md",
                   "docs/audits/2026-10-07-e6nk-electrode-source-context/check_gui.py",
                   "docs/audits/2026-10-07-e6nk-electrode-source-context/run_checks.py",
                   "tests/unit/test_electrode_source_context_mock.py",
                   "tests/unit/test_measurement_entry_point_gate_mock.py"],
        "outputs": [{"glob": "e6nk_out/**/*", "max_mb": 8}],
        "regenerate": "Actual Tk and DEVSIM import invalidation; synthetic CSV wiring; existing uniform DD control.",
    },
    "e6nj_measurement_validity": {
        "description": "Finite GUI measurement evidence boundary and failed DC retry; physical gates unchanged.",
        "entry": "docs/audits/2026-10-06-e6nj-measurement-validity/run_checks.py",
        "args": [], "params": {}, "timeout_s": 300, "engine_info": False,
        "inputs": ["tcad_2d_stagewise.py", "tcad/characterization/interface.py",
                   "docs/audits/2026-10-06-e6nj-measurement-validity/PLAN.md",
                   "docs/audits/2026-10-06-e6nj-measurement-validity/check_gui.py",
                   "docs/audits/2026-10-06-e6nj-measurement-validity/run_checks.py",
                   "tests/unit/test_measurement_validity_mock.py",
                   "tests/unit/test_measurement_entry_point_gate_mock.py"],
        "outputs": [{"glob": "e6nj_out/**/*", "max_mb": 8}],
        "regenerate": "Invalid input trapped before backend, existing supported uniform DD control; no PN approval.",
    },
    "e6ni_depth_doping": {
        "description": "Actual mesh-centroid canonical 2D doping display and depth hover, existing gates unchanged.",
        "entry": "docs/audits/2026-10-06-e6ni-depth-doping-display/run_checks.py",
        "args": [], "params": {}, "timeout_s": 400, "engine_info": False,
        "inputs": ["tcad_2d_stagewise.py", "docs/audits/2026-10-06-e6ni-depth-doping-display/PLAN.md",
                   "tcad/physics/wafer_state_v2.py",
                   "docs/audits/2026-10-06-e6ni-depth-doping-display/check_depth.py",
                   "docs/audits/2026-10-06-e6ni-depth-doping-display/check_invalid.py",
                   "docs/audits/2026-10-06-e6ni-depth-doping-display/run_checks.py",
                   "tests/unit/test_gui_depth_doping_mock.py"],
        "outputs": [{"glob": "e6ni_out/**/*", "max_mb": 8}],
        "regenerate": "Depth-aware Tk display on a ViennaPS virgin mesh; no implant or transport capability approval.",
    },
    "e6nh_canvas_contract": {
        "description": "Actual current-wafer canvas geometry source and unsupported disclosure; gates unchanged.",
        "entry": "docs/audits/2026-10-06-e6nh-canvas-source-contract/run_checks.py",
        "args": [], "params": {}, "timeout_s": 400, "engine_info": False,
        "inputs": ["tcad_2d_stagewise.py", "docs/audits/2026-10-06-e6nh-canvas-source-contract/PLAN.md",
                   "docs/audits/2026-10-06-e6nh-canvas-source-contract/check_canvas.py",
                   "docs/audits/2026-10-06-e6nh-canvas-source-contract/run_checks.py",
                   "tests/unit/test_gui_canvas_source_contract_mock.py"],
        "outputs": [{"glob": "e6nh_out/**/*", "max_mb": 8},
                    {"glob": "e6nh_before_out/**/*", "max_mb": 5}],
        "regenerate": "Actual Tk/ViennaPS contract and existing measurement control; no general gate release.",
    },
    "e6nh_canvas_before": {
        "description": "Reproduce actual Tk false geometry before the canvas fix; no solve.",
        "entry": "docs/audits/2026-10-06-e6nh-canvas-source-contract/check_canvas.py",
        "args": ["--before"], "params": {}, "timeout_s": 60, "engine_info": False,
        "inputs": ["tcad_2d_stagewise.py", "docs/audits/2026-10-06-e6nh-canvas-source-contract/PLAN.md",
                   "docs/audits/2026-10-06-e6nh-canvas-source-contract/check_canvas.py"],
        "outputs": [{"glob": "e6nh_before_out/**/*", "max_mb": 5}],
        "regenerate": "Read-only actual Tk reproduction on pre-fix source.",
    },
    "e6ng_render_only": {
        "description": "Actual Tk rendering of immutable successful PN result; no engine import or solve.",
        "entry": "docs/audits/2026-10-06-e6ng-pn-reference-gui/render_check.py",
        "args": [], "params": {}, "timeout_s": 60, "engine_info": False,
        "inputs": [
            "tcad/characterization/pn_reference_view.py",
            "docs/audits/2026-10-06-e6ng-pn-reference-gui/render_check.py",
            "docs/audits/2026-10-06-e6ng-pn-reference-gui/raw/outputs/e6ng_out/result.json"
        ],
        "outputs": [{"glob": "e6ng_render_out/**/*", "max_mb": 5}],
        "regenerate": "Render the immutable result without recalculation.",
    },
    "e6ng_pn_reference_gui": {
        "description": "Fixed 1D PN reference GUI with physical checks; existing 2D gate unchanged.",
        "entry": "docs/audits/2026-10-06-e6ng-pn-reference-gui/run_tests.py",
        "args": [], "params": {}, "timeout_s": 500, "engine_info": False,
        "inputs": [
            "docs/audits/2026-10-06-e6ng-pn-reference-gui/PLAN.md",
            "tcad/characterization/pn_reference.py",
            "tcad/characterization/pn_reference_view.py",
            "tcad/characterization/reference_data/pn_1d_arrays.npz",
            "tcad/characterization/reference_data/pn_1d_record.json",
            "tcad_2d_stagewise.py",
            "tests/unit/test_pn_reference_view_mock.py",
            "tests/integration/test_pn_reference_gui_real.py"
        ],
        "outputs": [{"glob": "e6ng_out/**/*", "max_mb": 15}],
        "regenerate": "GUI button runs a fresh fixed 1D reference; no general 2D gate release.",
    },
    "e6nf_reference_convergence": {
        "description": "Official 1D API interval bisection; 14 PN solves only, production gates unchanged.",
        "entry": "docs/audits/2026-10-06-e6nf-reference-convergence/convergence.py",
        "args": [], "params": {}, "timeout_s": 150, "engine_info": False,
        "inputs": [
            "docs/audits/2026-10-06-e6nf-reference-convergence/PLAN.md",
            "docs/audits/2026-10-06-e6nf-reference-convergence/convergence.py",
            "docs/audits/2026-10-06-e6ne-matched-1d-reference/run_reference.py",
            "docs/audits/2026-10-06-e6ne-matched-1d-reference/raw/outputs/e6ne_out/reference/arrays.npz",
            "docs/audits/2026-10-06-e6ne-matched-1d-reference/raw/outputs/e6ne_out/reference/record.json"
        ],
        "outputs": [{"glob": "e6nf_out/**/*", "max_mb": 10}],
        "regenerate": "Official 1D API only; no new 2D solves or gate release.",
    },
    "e6ne_matched_1d_reference": {
        "description": "Exact-x 1D numerical PN reference; reuse N2 2D evidence without new 2D solves or gate changes.",
        "entry": "docs/audits/2026-10-06-e6ne-matched-1d-reference/run_reference.py",
        "args": [], "params": {}, "timeout_s": 330, "engine_info": False,
        "inputs": [
            "docs/audits/2026-10-06-e6ne-matched-1d-reference/PLAN.md",
            "docs/audits/2026-10-06-e6ne-matched-1d-reference/common.py",
            "docs/audits/2026-10-06-e6ne-matched-1d-reference/run_reference.py",
            "docs/audits/2026-10-06-e6ne-matched-1d-reference/matched_judge.py",
            "docs/audits/2026-10-06-e6ne-matched-1d-reference/test_contract.py",
            "docs/audits/2026-10-06-e6nd-pn-transition-pilot/raw_fine/outputs/e6nd_fine_out/N2/arrays.npz",
            "docs/audits/2026-10-06-e6nd-pn-transition-pilot/raw_fine/outputs/e6nd_fine_out/N2/record.json",
            "tcad/characterization/pn_junction_iv_sweep.py",
            "tcad/device/devsim/semiconductor_equation.py",
            "tcad/device/devsim/doping_mapping.py"
        ],
        "outputs": [{"glob": "e6ne_out/**/*", "max_mb": 20}],
        "regenerate": "Only three fresh 1D devices, 17 solves planned; never release production PN gate.",
    },
    "e6nd_pn_fine_diagnostic": {
        "description": "Post-hoc N2-only PN diagnostic; old two-mesh failure retained, production gate closed.",
        "entry": "docs/audits/2026-10-06-e6nd-pn-transition-pilot/fine_pilot.py",
        "args": [], "params": {}, "timeout_s": 930, "engine_info": False,
        "inputs": [
            "docs/audits/2026-10-06-e6nd-pn-transition-pilot/PLAN.md",
            "docs/audits/2026-10-06-e6nd-pn-transition-pilot/PLAN_FINE.md",
            "docs/audits/2026-10-06-e6nd-pn-transition-pilot/fine_pilot.py",
            "docs/audits/2026-10-06-e6nd-pn-transition-pilot/pilot.py",
            "docs/audits/2026-10-06-e6nd-pn-transition-pilot/judge.py",
            "docs/audits/2026-10-06-e6nd-pn-transition-pilot/raw/outputs/e6nd_out/result.json"
        ],
        "outputs": [{"glob": "e6nd_fine_out/**/*", "max_mb": 120}],
        "regenerate": "Only N2; preserve prior failed physical acceptance and all production gates.",
    },
    "e6nd_pn_transition_pilot": {
        "description": "Preregistered two-level symmetric PN transition mesh audit; production gate remains closed.",
        "entry": "docs/audits/2026-10-06-e6nd-pn-transition-pilot/pilot.py",
        "args": [], "params": {}, "timeout_s": 1830, "engine_info": False,
        "inputs": [
            "docs/audits/2026-10-06-e6nd-pn-transition-pilot/PLAN.md",
            "docs/audits/2026-10-06-e6nd-pn-transition-pilot/pilot.py",
            "docs/audits/2026-10-06-e6nd-pn-transition-pilot/judge.py",
            "docs/audits/2026-10-06-e6nd-pn-transition-pilot/test_contract.py",
            "tests/integration/test_pn_2d_1d_consistency_real.py",
            "tcad/characterization/pn_junction_iv_sweep.py",
            "tcad/device/devsim/mesh_refine.py",
            "tcad/device/devsim/mesh_import.py",
            "tcad/device/devsim/doping_mapping.py",
            "docs/audits/2026-10-01-e6k-pn-1d-diagnostic/data/remote_run_36815925901/remote-run-31/outputs/e6k_out/states.npz",
            "docs/audits/2026-10-01-e6k-pn-1d-diagnostic/data/remote_run_36815925901/remote-run-31/outputs/e6k_out/pn_1d_diagnostic.json"
        ],
        "outputs": [{"glob": "e6nd_out/**/*", "max_mb": 120}],
        "regenerate": "Fixed PLAN pilot only; never release production PN gate.",
    },
    "e6nc_pn_completion_revalidation": {
        "description": "Engine-free PN evidence revalidation and rejection of incomplete audit success; no physical solve.",
        "entry": "docs/audits/2026-10-06-e6nc-pn-completion-contract/revalidate.py",
        "args": [], "params": {}, "timeout_s": 120, "engine_info": False,
        "inputs": [
            "docs/audits/2026-10-06-e6nc-pn-completion-contract/PLAN.md",
            "docs/audits/2026-10-06-e6nc-pn-completion-contract/revalidate.py",
            "docs/audits/2026-10-02-e6m-pn-2d-1d-consistency/scripts/judge_e6m.py",
            "docs/audits/2026-10-02-e6m-pn-2d-1d-consistency/scripts/e6m_metrics.py",
            "tests/integration/test_pn_2d_1d_consistency_real.py",
            "tests/unit/test_e6m_completion_exit_mock.py",
            "tests/unit/test_e6m_judge_mock.py",
            "tests/unit/test_e6m_execution_contract_mock.py",
            "tests/unit/test_e6l_correction_mock.py"
        ],
        "outputs": [{"glob": "e6nc_out/**/*", "max_mb": 10}],
        "regenerate": "Recheck stored evidence only; incomplete historical PN is not approved.",
    },
    "e6nb_native_2d_control": {
        "description": "Fixed native positive/negative controls and four manufactured 2D Poisson solves; not PN physics.",
        "entry": "docs/audits/2026-10-06-e6nb-native-2d-control/run_control.py",
        "args": [], "params": {}, "timeout_s": 150, "engine_info": False,
        "inputs": [
            "docs/audits/2026-10-06-e6nb-native-2d-control/PLAN.md",
            "docs/audits/2026-10-06-e6nb-native-2d-control/run_control.py",
            "docs/audits/2026-10-06-e6nb-native-2d-control/test_contract.py",
            "docs/audits/2026-10-06-e6nb-native-2d-control/SNAPSHOT_CORRECTION.md",
            "docs/audits/2026-10-02-e6na-import-reduction/diagnostics.py",
            "docs/audits/2026-10-02-e6na-import-reduction/flux_source_contract.py",
            "docs/audits/2026-10-02-e6na-import-reduction/resource_supervisor.py",
            "docs/audits/2026-10-02-e6na-import-reduction/run_e6na.py",
            "docs/audits/2026-10-02-e6na-import-reduction/test_positive_geometry.py",
            "docs/audits/2026-10-02-e6na-import-reduction/test_review_followup.py",
            "docs/audits/2026-10-02-e6na-import-reduction/POSITIVE_GEOMETRY_CRITERIA.md",
            "tcad/device/devsim/mesh_refine.py",
            "tcad/device/devsim/mesh_import.py"
        ],
        "outputs": [{"glob": "e6nb_out/**/*", "max_mb": 50}],
        "regenerate": "Independent fixed-plan 2D numerical audit; never release PN or process gates.",
    },
    "e6na_engine_free_compatibility": {
        "description": "E6N-A Python 3.11 / nested Windows Job / AST / synthetic geometry controls; engine import forbidden.",
        "entry": "docs/audits/2026-10-06-e6na-compatibility/run_compatibility.py",
        "args": [], "params": {}, "timeout_s": 120, "engine_info": False,
        "inputs": [
            "docs/audits/2026-10-06-e6na-compatibility/PLAN.md",
            "docs/audits/2026-10-06-e6na-compatibility/run_compatibility.py",
            "docs/audits/2026-10-02-e6na-import-reduction/run_e6na.py",
            "docs/audits/2026-10-02-e6na-import-reduction/diagnostics.py",
            "docs/audits/2026-10-02-e6na-import-reduction/flux_source_contract.py",
            "docs/audits/2026-10-02-e6na-import-reduction/resource_supervisor.py",
            "docs/audits/2026-10-02-e6na-import-reduction/REVIEWED_FLUX_REFERENCE.txt",
            "docs/audits/2026-10-02-e6na-import-reduction/RESOURCE_EXECUTION_CONTRACT.md",
            "docs/audits/2026-10-02-e6na-import-reduction/POSITIVE_GEOMETRY_CRITERIA.md",
            "docs/audits/2026-10-02-e6na-import-reduction/test_contract.py",
            "docs/audits/2026-10-02-e6na-import-reduction/test_review_followup.py",
            "docs/audits/2026-10-02-e6na-import-reduction/test_flux_source_contract.py",
            "docs/audits/2026-10-02-e6na-import-reduction/test_resource_supervisor.py",
            "docs/audits/2026-10-02-e6na-import-reduction/test_supervised_entry.py",
            "docs/audits/2026-10-02-e6na-import-reduction/test_positive_geometry.py",
            "docs/audits/2026-10-02-e6m-pn-2d-1d-consistency/scripts/e6m_metrics.py",
            "docs/audits/2026-10-01-batch7h-e6h-conformity-poisson/scripts/conformity_e6h.py"
        ],
        "outputs": [{"glob": "e6na_compat_out/**/*", "max_mb": 5}],
        "regenerate": "Engine-free compatibility only. No PN or real mesh import approval.",
    },
    "e6na_import_reduction": {
        "description": "E6N-A fixed-plan official import and discrete reduction diagnostics; no solve calls permitted.",
        "entry": "docs/audits/2026-10-02-e6na-import-reduction/run_e6na.py",
        "args": [], "params": {}, "timeout_s": 1830, "engine_info": False,
        "inputs": [
            "docs/audits/2026-10-02-e6na-import-reduction/PLAN.md",
            "docs/audits/2026-10-02-e6na-import-reduction/run_e6na.py",
            "docs/audits/2026-10-02-e6na-import-reduction/diagnostics.py",
            "docs/audits/2026-10-02-e6na-import-reduction/flux_source_contract.py",
            "docs/audits/2026-10-02-e6na-import-reduction/REVIEWED_FLUX_REFERENCE.txt",
            "docs/audits/2026-10-02-e6na-import-reduction/resource_supervisor.py",
            "docs/audits/2026-10-02-e6na-import-reduction/RESOURCE_EXECUTION_CONTRACT.md",
            "docs/audits/2026-10-02-e6na-import-reduction/test_resource_supervisor.py",
            "docs/audits/2026-10-02-e6na-import-reduction/test_contract.py",
            "docs/audits/2026-10-02-e6m-pn-2d-1d-consistency/e6n_geometry_result.json",
            "docs/audits/2026-10-02-e6m-pn-2d-1d-consistency/GEOMETRY_DESIGN_RULE.md",
            "docs/audits/2026-10-02-e6m-pn-2d-1d-consistency/scripts/e6m_metrics.py",
            "docs/audits/2026-10-02-e6m-pn-2d-1d-consistency/scripts/judge_e6m.py",
            "tests/integration/test_pn_2d_1d_consistency_real.py",
            "tcad/device/devsim/mesh_refine.py",
            "tcad/device/devsim/mesh_import.py",
            "docs/audits/2026-10-01-batch7h-e6h-conformity-poisson/scripts/conformity_e6h.py",
            "docs/audits/2026-10-01-e6k-pn-1d-diagnostic/data/remote_run_36815925901/remote-run-31/outputs/e6k_out/states.npz"
        ],
        "outputs": [{"glob": "e6na_out/**/*", "max_mb": 120}],
        "regenerate": "Only rerun after explicit approval; no solve permitted.",
    },
    "phase5_smoke": {
        "description": "Small real check: ViennaPS etch -> ProcessResult -> DevSim Laplace solve.",
        "entry": "tests/integration/test_phase5_devsim_real.py",
        "args": [],
        "params": {},                       # name -> {"choices": [...]} | {"int": [min, max]}
        "timeout_s": 600,
        "inputs": ["tests/integration/test_phase5_devsim_real.py"],
        "outputs": [],                      # [{"glob": "relative/glob", "max_mb": N}, ...] uploaded if within budget
        "regenerate": "Rerun this profile; the test writes only to a temp directory and produces no artifact.",
    },
    "d3_precision_mirror": {
        "description": "Batch 7H-D3: P0/P12/P4 precision pair on M2/D0 h=0.005 um and corrected mirror re-check (11 small runs + analysis).",
        "entry": "docs/audits/2026-09-24-batch7h-d3-precision-pair-mirror/scripts/run_d3.py",
        "args": [],
        "params": {},
        "timeout_s": 3600,
        "inputs": [
            "docs/audits/2026-09-24-batch7h-d3-precision-pair-mirror/PLAN.md",
            "docs/audits/2026-09-24-batch7h-d3-precision-pair-mirror/PLAN.sha256",
            "docs/audits/2026-09-24-batch7h-d3-precision-pair-mirror/PLAN_ERRATA.md",
            "docs/audits/2026-09-24-batch7h-d3-precision-pair-mirror/scripts/run_d3.py",
            "docs/audits/2026-09-24-batch7h-d3-precision-pair-mirror/scripts/worker_d3.py",
            "docs/audits/2026-09-24-batch7h-d3-precision-pair-mirror/scripts/analyze_d3.py",
            "docs/audits/2026-09-23-batch7h-d1-pn-convergence/data/fixtures_d1.json",
            "docs/audits/2026-09-23-batch7h-d2-current-precision/scripts/worker_d2.py",
            "docs/audits/2026-09-23-batch7h-d2-current-precision/scripts/common_d2.py",
            "docs/audits/2026-09-23-batch7h-d2-current-precision/data/fixed_d2.json",
        ],
        "outputs": [{"glob": "d3_out/**/*.json", "max_mb": 50}, {"glob": "d3_out/**/*.md", "max_mb": 5}],
        "regenerate": "Rerun the profile (about 10 small runs, minutes). Nothing is omitted: every run JSON and the analysis are uploaded.",
    },
    "d4_precision_generality": {
        "description": "Batch 7H-D4: P12 vs P4 on M1/D0 h=0.005, M1/D0 h=0.00125, M2/D0 h=0.00125 um (6 runs) with fail-closed evidence gate.",
        "entry": "docs/audits/2026-09-24-batch7h-d4-precision-generality/scripts/run_d4.py",
        "args": [],
        "params": {},
        "timeout_s": 18000,
        "inputs": [
            "docs/audits/2026-09-24-batch7h-d4-precision-generality/PLAN.md",
            "docs/audits/2026-09-24-batch7h-d4-precision-generality/PLAN.sha256",
            "docs/audits/2026-09-24-batch7h-d4-precision-generality/scripts/run_d4.py",
            "docs/audits/2026-09-24-batch7h-d4-precision-generality/scripts/worker_d4.py",
            "docs/audits/2026-09-24-batch7h-d4-precision-generality/scripts/analyze_d4.py",
            "docs/audits/2026-09-24-batch7h-d3-precision-pair-mirror/scripts/worker_d3.py",
            "docs/audits/2026-09-24-batch7h-d3-precision-pair-mirror/scripts/analyze_d3.py",
            "docs/audits/2026-09-23-batch7h-d2-current-precision/scripts/build_fixtures_d2.py",
            "docs/audits/2026-09-23-batch7h-d2-current-precision/scripts/worker_d2.py",
            "docs/audits/2026-09-23-batch7h-d2-current-precision/scripts/common_d2.py",
            "docs/audits/2026-09-23-batch7h-d2-current-precision/data/fixed_d2.json",
            "docs/audits/2026-09-23-batch7h-d1-pn-convergence/data/fixtures_d1.json",
        ],
        "outputs": [{"glob": "d4_out/**/*.json", "max_mb": 50}, {"glob": "d4_out/**/*.npz", "max_mb": 50}],
        "regenerate": "Rerun the profile. fixtures_d2.json is regenerated by build_fixtures_d2.py and hash-gated (e2c018a6...).",
    },
    "e1_production_step_junction": {
        "description": "Batch 7H-E1: production GUI step-junction path (ViennaPS mesh -> WaferStateV2 -> DEVSIM import), gate control, pre-checks, audit-only shadows S0/S12.",
        "entry": "docs/audits/2026-09-24-batch7h-e1-production-step-junction-equivalence/scripts/run_e1.py",
        "args": [],
        "params": {},
        "timeout_s": 18000,
        "inputs": [
            "docs/audits/2026-09-24-batch7h-e1-production-step-junction-equivalence/PLAN.md",
            "docs/audits/2026-09-24-batch7h-e1-production-step-junction-equivalence/PLAN.sha256",
            "docs/audits/2026-09-24-batch7h-e1-production-step-junction-equivalence/scripts/run_e1.py",
            "docs/audits/2026-09-24-batch7h-e1-production-step-junction-equivalence/scripts/common_e1.py",
            "docs/audits/2026-09-24-batch7h-e1-production-step-junction-equivalence/scripts/prod_build_e1.py",
            "docs/audits/2026-09-24-batch7h-e1-production-step-junction-equivalence/scripts/shadow_e1.py",
            "docs/audits/2026-09-24-batch7h-e1-production-step-junction-equivalence/scripts/analyze_e1.py",
            "docs/audits/2026-09-23-batch7h-d-sg-pn-mesh-validity/scripts/build_fixtures_7hd.py",
            "docs/audits/2026-09-23-batch7h-d-sg-pn-mesh-validity/scripts/meshes_7hd.py",
            "docs/audits/2026-09-23-batch7h-d-sg-pn-mesh-validity/scripts/sg_lib.py",
            "docs/audits/2026-09-23-batch7h-c-flux-discretization/scripts/meshes.py",
            "docs/audits/2026-09-23-batch7h-b-nodevolume-mechanism/scripts/formulas.py",
            "docs/audits/2026-09-23-batch7h-exact-flip-certification/scripts/exact_flip.py",
            "docs/audits/2026-09-23-batch7h-exact-flip-certification/scripts/exact_geometry.py",
            "docs/audits/2026-09-23-batch7h-d2-current-precision/data/fixed_d2.json",
            "docs/audits/2026-09-23-batch7h-d1-pn-convergence/data/fixtures_d1.json",
            "tcad_2d_stagewise.py",
        ],
        "outputs": [{"glob": "e1_out/**/*.json", "max_mb": 50}, {"glob": "e1_out/**/*.npz", "max_mb": 50}],
        "regenerate": "Rerun the profile. Production mesh is regenerated by ViennaPS from the GUI defaults in common_e1.py.",
    },
    "e2_nodevolume_first_bad_stage": {
        "description": "Batch 7H-E2: production-mesh NodeVolume excess, refinement passes 0-4 + writer / CCW controls + one conditional exact-flip candidate. No solve.",
        "entry": "docs/audits/2026-09-25-batch7h-e2-nodevolume-first-bad-stage/scripts/run_e2.py",
        "args": [],
        "params": {},
        "timeout_s": 18000,
        "inputs": [
            "docs/audits/2026-09-25-batch7h-e2-nodevolume-first-bad-stage/PLAN.md",
            "docs/audits/2026-09-25-batch7h-e2-nodevolume-first-bad-stage/PLAN.sha256",
            "docs/audits/2026-09-25-batch7h-e2-nodevolume-first-bad-stage/scripts/run_e2.py",
            "docs/audits/2026-09-25-batch7h-e2-nodevolume-first-bad-stage/scripts/stage_e2.py",
            "docs/audits/2026-09-25-batch7h-e2-nodevolume-first-bad-stage/scripts/trace_refine_e2.py",
            "docs/audits/2026-09-25-batch7h-e2-nodevolume-first-bad-stage/scripts/verdicts_e2.py",
            "docs/audits/2026-09-24-batch7h-e1-production-step-junction-equivalence/scripts/common_e1.py",
            "docs/audits/2026-09-24-batch7h-e1-production-step-junction-equivalence/data/remote_run_36012608804/outputs/e1_out/prod.json",
            "docs/audits/2026-09-24-batch7h-e1-production-step-junction-equivalence/data/remote_run_36012608804/outputs/e1_out/prod_arrays.npz",
            "docs/audits/2026-09-23-batch7h-d-sg-pn-mesh-validity/scripts/build_fixtures_7hd.py",
            "docs/audits/2026-09-23-batch7h-d-sg-pn-mesh-validity/scripts/meshes_7hd.py",
            "docs/audits/2026-09-23-batch7h-d-sg-pn-mesh-validity/scripts/sg_lib.py",
            "docs/audits/2026-09-23-batch7h-c-flux-discretization/scripts/meshes.py",
            "docs/audits/2026-09-23-batch7h-b-nodevolume-mechanism/scripts/formulas.py",
            "docs/audits/2026-09-23-batch7h-exact-flip-certification/scripts/exact_flip.py",
            "docs/audits/2026-09-23-batch7h-exact-flip-certification/scripts/exact_geometry.py",
            "tcad/device/devsim/mesh_import.py",
            "tcad/device/devsim/mesh_refine.py",
        ],
        "outputs": [{"glob": "e2_out/**/*.json", "max_mb": 50}, {"glob": "e2_out/**/*.npz", "max_mb": 50},
                    {"glob": "e2_out/**/*.vtu", "max_mb": 50}],
        "regenerate": "Rerun the profile. The wafer mesh is regenerated by ViennaPS and hash-gated against E1 (cfae97d4...).",
    },
    "e3_junction_refinement_candidate": {
        "description": "Batch 7H-E3: one audit-only graded-refinement candidate for the step-junction mesh (reuses production graded_refine_mesh_near unmodified), geometry + DEVSIM NodeVolume/EdgeCouple checks only. No solve.",
        "entry": "docs/audits/2026-09-25-batch7h-e3-junction-refinement-candidate/scripts/run_e3.py",
        "args": [],
        "params": {},
        "timeout_s": 10000,
        "inputs": [
            "docs/audits/2026-09-25-batch7h-e3-junction-refinement-candidate/PLAN.md",
            "docs/audits/2026-09-25-batch7h-e3-junction-refinement-candidate/PLAN.sha256",
            "docs/audits/2026-09-25-batch7h-e3-junction-refinement-candidate/scripts/run_e3.py",
            "docs/audits/2026-09-25-batch7h-e3-junction-refinement-candidate/scripts/stage_e3.py",
            "docs/audits/2026-09-25-batch7h-e2-nodevolume-first-bad-stage/scripts/trace_refine_e2.py",
            "docs/audits/2026-09-25-batch7h-e2-nodevolume-first-bad-stage/scripts/stage_e2.py",
            "docs/audits/2026-09-25-batch7h-e2-nodevolume-first-bad-stage/data/remote_run_36129959490/outputs/e2_out/e2_result.json",
            "docs/audits/2026-09-25-batch7h-e2-nodevolume-first-bad-stage/data/remote_run_36129959490/outputs/e2_out/stage_S4.npz",
            "docs/audits/2026-09-24-batch7h-e1-production-step-junction-equivalence/scripts/common_e1.py",
            "docs/audits/2026-09-24-batch7h-e1-production-step-junction-equivalence/data/remote_run_36012608804/outputs/e1_out/prod.json",
            "docs/audits/2026-09-24-batch7h-e1-production-step-junction-equivalence/data/remote_run_36012608804/outputs/e1_out/prod_arrays.npz",
            "docs/audits/2026-09-23-batch7h-d-sg-pn-mesh-validity/scripts/build_fixtures_7hd.py",
            "docs/audits/2026-09-23-batch7h-d-sg-pn-mesh-validity/scripts/meshes_7hd.py",
            "docs/audits/2026-09-23-batch7h-d-sg-pn-mesh-validity/scripts/sg_lib.py",
            "docs/audits/2026-09-23-batch7h-c-flux-discretization/scripts/meshes.py",
            "docs/audits/2026-09-23-batch7h-b-nodevolume-mechanism/scripts/formulas.py",
            "docs/audits/2026-09-23-batch7h-exact-flip-certification/scripts/exact_flip.py",
            "docs/audits/2026-09-23-batch7h-exact-flip-certification/scripts/exact_geometry.py",
            "tcad/device/devsim/mesh_import.py",
            "tcad/device/devsim/mesh_refine.py",
            "tcad/physics/wafer_state_v2.py",
            "tcad/physics/wafer_state_accumulation.py",
            "tcad/physics/doping.py",
        ],
        "outputs": [{"glob": "e3_out/**/*.json", "max_mb": 50}, {"glob": "e3_out/**/*.npz", "max_mb": 50},
                    {"glob": "e3_out/**/*.vtu", "max_mb": 50}],
        "regenerate": "Rerun the profile. The wafer mesh is regenerated by ViennaPS and hash-gated against E1/E2 (cfae97d4...).",
    },
    "e4_nonobtuse_quadtree_candidate": {
        "description": "Batch 7H-E4: production S4 fine region kept, 0.1-0.2 um transition strips re-filled with a non-obtuse 2:1 quadtree template; geometry + DEVSIM NodeVolume/EdgeCouple only. No solve.",
        "entry": "docs/audits/2026-09-25-batch7h-e4-nonobtuse-quadtree-candidate/scripts/run_e4.py",
        "args": [],
        "params": {},
        "timeout_s": 10000,
        "inputs": [
            "docs/audits/2026-09-25-batch7h-e4-nonobtuse-quadtree-candidate/PLAN.md",
            "docs/audits/2026-09-25-batch7h-e4-nonobtuse-quadtree-candidate/PLAN.sha256",
            "docs/audits/2026-09-25-batch7h-e4-nonobtuse-quadtree-candidate/scripts/run_e4.py",
            "docs/audits/2026-09-25-batch7h-e4-nonobtuse-quadtree-candidate/scripts/stage_e4.py",
            "docs/audits/2026-09-25-batch7h-e4-nonobtuse-quadtree-candidate/scripts/quadtree_e4.py",
            "docs/audits/2026-09-25-batch7h-e3-junction-refinement-candidate/scripts/stage_e3.py",
            "docs/audits/2026-09-25-batch7h-e2-nodevolume-first-bad-stage/scripts/trace_refine_e2.py",
            "docs/audits/2026-09-25-batch7h-e2-nodevolume-first-bad-stage/scripts/stage_e2.py",
            "docs/audits/2026-09-25-batch7h-e2-nodevolume-first-bad-stage/data/remote_run_36129959490/outputs/e2_out/e2_result.json",
            "docs/audits/2026-09-25-batch7h-e2-nodevolume-first-bad-stage/data/remote_run_36129959490/outputs/e2_out/stage_S0.npz",
            "docs/audits/2026-09-25-batch7h-e2-nodevolume-first-bad-stage/data/remote_run_36129959490/outputs/e2_out/stage_S4.npz",
            "docs/audits/2026-09-24-batch7h-e1-production-step-junction-equivalence/scripts/common_e1.py",
            "docs/audits/2026-09-24-batch7h-e1-production-step-junction-equivalence/data/remote_run_36012608804/outputs/e1_out/prod.json",
            "docs/audits/2026-09-24-batch7h-e1-production-step-junction-equivalence/data/remote_run_36012608804/outputs/e1_out/prod_arrays.npz",
            "docs/audits/2026-09-23-batch7h-d-sg-pn-mesh-validity/scripts/build_fixtures_7hd.py",
            "docs/audits/2026-09-23-batch7h-d-sg-pn-mesh-validity/scripts/meshes_7hd.py",
            "docs/audits/2026-09-23-batch7h-d-sg-pn-mesh-validity/scripts/sg_lib.py",
            "docs/audits/2026-09-23-batch7h-c-flux-discretization/scripts/meshes.py",
            "docs/audits/2026-09-23-batch7h-b-nodevolume-mechanism/scripts/formulas.py",
            "docs/audits/2026-09-23-batch7h-exact-flip-certification/scripts/exact_flip.py",
            "docs/audits/2026-09-23-batch7h-exact-flip-certification/scripts/exact_geometry.py",
            "tcad/device/devsim/mesh_import.py",
            "tcad/device/devsim/mesh_refine.py",
            "tcad/physics/wafer_state_v2.py",
            "tcad/physics/wafer_state_accumulation.py",
            "tcad/physics/doping.py",
        ],
        "outputs": [{"glob": "e4_out/**/*.json", "max_mb": 50}, {"glob": "e4_out/**/*.npz", "max_mb": 50},
                    {"glob": "e4_out/**/*.vtu", "max_mb": 50}],
        "regenerate": "Rerun the profile. The wafer mesh is regenerated by ViennaPS and hash-gated against E1-E3 (cfae97d4...).",
    },
    "e5_equilibrium_pilot": {
        "description": "Batch 7H-E5: 0V equilibrium electrical pilot on the 7H-E4 candidate mesh (audit-only device, real devsim.solve calls, no bias ramp). 6 runs: {D2D,D1D_J0,D1D_J1}x{S0,S12}.",
        "entry": "docs/audits/2026-09-25-batch7h-e5-equilibrium-pilot/scripts/run_e5.py",
        "args": [],
        "params": {},
        "timeout_s": 10000,
        "inputs": [
            "docs/audits/2026-09-25-batch7h-e5-equilibrium-pilot/PLAN.md",
            "docs/audits/2026-09-25-batch7h-e5-equilibrium-pilot/PLAN.sha256",
            "docs/audits/2026-09-25-batch7h-e5-equilibrium-pilot/scripts/run_e5.py",
            "docs/audits/2026-09-25-batch7h-e5-equilibrium-pilot/scripts/stage_e5.py",
            "docs/audits/2026-09-25-batch7h-e5-equilibrium-pilot/scripts/devices_e5.py",
            "docs/audits/2026-09-25-batch7h-e4-nonobtuse-quadtree-candidate/data/remote_run_36143535737/outputs/e4_out/candidate_e4.vtu",
            "docs/audits/2026-09-25-batch7h-e4-nonobtuse-quadtree-candidate/data/remote_run_36143535737/outputs/e4_out/e4_result.json",
            "docs/audits/2026-09-24-batch7h-e1-production-step-junction-equivalence/scripts/common_e1.py",
            "docs/audits/2026-09-24-batch7h-e1-production-step-junction-equivalence/scripts/shadow_e1.py",
            "docs/audits/2026-09-23-batch7h-d1-pn-convergence/scripts/common_d1.py",
            "docs/audits/2026-09-23-batch7h-d1-pn-convergence/scripts/meshes_d1.py",
            "docs/audits/2026-09-23-batch7h-d1-pn-convergence/data/fixed_d1.json",
            "tcad/device/devsim/semiconductor_equation.py",
            "tcad/device/devsim/doping_mapping.py",
            "tcad/device/devsim/mesh_import.py",
            "tcad/mesh/viennaps_adapter.py",
            "tcad/characterization/pn_junction_iv_sweep.py",
            "tcad/physics/wafer_state_v2.py",
        ],
        "outputs": [{"glob": "e5_out/**/*.json", "max_mb": 50}],
        "regenerate": "Rerun the profile. All 6 runs are built and solved fresh each time; no cached state.",
    },
    "e6a_mesh_family": {
        "description": "Batch 7H-E6A: non-obtuse conforming mesh family L3/L4/L5 (7H-E4 rule generalized); geometry + DEVSIM NodeVolume only. No solve.",
        "entry": "docs/audits/2026-09-28-batch7h-e6a-mesh-family/scripts/run_e6a.py",
        "args": [],
        "params": {},
        "timeout_s": 9000,
        "inputs": [
            "docs/audits/2026-09-28-batch7h-e6a-mesh-family/PLAN.md",
            "docs/audits/2026-09-28-batch7h-e6a-mesh-family/PLAN.sha256",
            "docs/audits/2026-09-28-batch7h-e6a-mesh-family/scripts/run_e6a.py",
            "docs/audits/2026-09-28-batch7h-e6a-mesh-family/scripts/stage_e6a.py",
            "docs/audits/2026-09-28-batch7h-e6a-mesh-family/scripts/family_e6a.py",
            "docs/audits/2026-09-25-batch7h-e4-nonobtuse-quadtree-candidate/scripts/quadtree_e4.py",
            "docs/audits/2026-09-25-batch7h-e4-nonobtuse-quadtree-candidate/data/remote_run_36143535737/outputs/e4_out/candidate_e4.vtu",
            "docs/audits/2026-09-25-batch7h-e4-nonobtuse-quadtree-candidate/data/remote_run_36143535737/outputs/e4_out/candidate_e4.npz",
            "docs/audits/2026-09-25-batch7h-e4-nonobtuse-quadtree-candidate/data/remote_run_36143535737/outputs/e4_out/e4_result.json",
            "docs/audits/2026-09-25-batch7h-e2-nodevolume-first-bad-stage/scripts/stage_e2.py",
            "docs/audits/2026-09-25-batch7h-e2-nodevolume-first-bad-stage/scripts/trace_refine_e2.py",
            "docs/audits/2026-09-25-batch7h-e2-nodevolume-first-bad-stage/scripts/verdicts_e2.py",
            "docs/audits/2026-09-24-batch7h-e1-production-step-junction-equivalence/scripts/common_e1.py",
            "docs/audits/2026-09-23-batch7h-b-nodevolume-mechanism/scripts/formulas.py",
            "tcad/device/devsim/mesh_import.py",
            "tcad/device/devsim/mesh_refine.py",
            "tcad/mesh/viennaps_adapter.py",
            "tcad/physics/doping.py",
            "tcad/backends/viennaps/io.py",
            "tcad/backends/viennaps/session.py",
        ],
        "outputs": [{"glob": "e6a_out/**/*.json", "max_mb": 50}, {"glob": "e6a_out/**/*.npz", "max_mb": 50},
                    {"glob": "e6a_out/**/*.vtu", "max_mb": 50}],
        "regenerate": "Rerun the profile. The wafer mesh is regenerated by ViennaPS and hash-gated (cfae97d4...); every level is rebuilt.",
    },    "e6b_poisson_junction_refinement": {
        "description": "Batch 7H-E6B: 0 V Poisson-only junction-refinement trend on the E6A L3/L4/L5 meshes (audit device, J0 doping, at most 10 devsim.solve calls) plus a 1D reference R6/R7.",
        "entry": "docs/audits/2026-09-28-batch7h-e6b-poisson-junction-refinement/scripts/run_e6b.py",
        "args": [],
        "params": {},
        "timeout_s": 9000,
        "inputs": [
            "docs/audits/2026-09-28-batch7h-e6b-poisson-junction-refinement/PLAN.md",
            "docs/audits/2026-09-28-batch7h-e6b-poisson-junction-refinement/PLAN.sha256",
            "docs/audits/2026-09-28-batch7h-e6b-poisson-junction-refinement/PLAN_REVISION.md",
            "docs/audits/2026-09-28-batch7h-e6b-poisson-junction-refinement/scripts/run_e6b.py",
            "docs/audits/2026-09-28-batch7h-e6b-poisson-junction-refinement/scripts/stage_e6b.py",
            "docs/audits/2026-09-28-batch7h-e6b-poisson-junction-refinement/scripts/judge_e6b.py",
            "docs/audits/2026-09-28-batch7h-e6a-mesh-family/PLAN.md",
            "docs/audits/2026-09-28-batch7h-e6a-mesh-family/data/remote_run_36388479824/outputs/e6a_out/e6a_result.json",
            "docs/audits/2026-09-28-batch7h-e6a-mesh-family/data/remote_run_36388479824/outputs/e6a_out/level_L3.vtu",
            "docs/audits/2026-09-28-batch7h-e6a-mesh-family/data/remote_run_36388479824/outputs/e6a_out/level_L4.vtu",
            "docs/audits/2026-09-28-batch7h-e6a-mesh-family/data/remote_run_36388479824/outputs/e6a_out/level_L5.vtu",
            "docs/audits/2026-09-28-batch7h-e6a-mesh-family/data/remote_run_36388479824/outputs/e6a_out/level_L3.npz",
            "docs/audits/2026-09-28-batch7h-e6a-mesh-family/data/remote_run_36388479824/outputs/e6a_out/level_L4.npz",
            "docs/audits/2026-09-28-batch7h-e6a-mesh-family/data/remote_run_36388479824/outputs/e6a_out/level_L5.npz",
            "docs/audits/2026-09-24-batch7h-e1-production-step-junction-equivalence/scripts/common_e1.py",
            "tcad/device/devsim/mesh_import.py",
            "tcad/device/devsim/semiconductor_equation.py",
            "tcad/mesh/viennaps_adapter.py",
        ],
        "outputs": [{"glob": "e6b_out/**/*.json", "max_mb": 50}, {"glob": "e6b_out/**/*.npz", "max_mb": 80}],
        "regenerate": "Rerun the profile. Every device is imported/built fresh in its own process; E6A inputs are hash-gated.",
    },    "e6c_initialization_robustness": {
        "description": "Batch 7H-E6C: 0 V Poisson-only, E6A L3/L4/L5, two independent initial potentials (P default, Q linear contact-to-contact), one devsim.solve per process, at most 6 solves.",
        "entry": "docs/audits/2026-09-29-batch7h-e6c-initialization-robustness/scripts/run_e6c.py",
        "args": [],
        "params": {},
        "timeout_s": 9000,
        "inputs": [
            "docs/audits/2026-09-29-batch7h-e6c-initialization-robustness/PLAN.md",
            "docs/audits/2026-09-29-batch7h-e6c-initialization-robustness/PLAN.sha256",
            "docs/audits/2026-09-29-batch7h-e6c-initialization-robustness/scripts/run_e6c.py",
            "docs/audits/2026-09-29-batch7h-e6c-initialization-robustness/scripts/stage_e6c.py",
            "docs/audits/2026-09-29-batch7h-e6c-initialization-robustness/scripts/judge_e6c.py",
            "docs/audits/2026-09-28-batch7h-e6b-poisson-junction-refinement/PLAN.md",
            "docs/audits/2026-09-28-batch7h-e6b-poisson-junction-refinement/scripts/judge_e6b.py",
            "docs/audits/2026-09-28-batch7h-e6a-mesh-family/PLAN.md",
            "docs/audits/2026-09-28-batch7h-e6a-mesh-family/data/remote_run_36388479824/outputs/e6a_out/e6a_result.json",
            "docs/audits/2026-09-28-batch7h-e6a-mesh-family/data/remote_run_36388479824/outputs/e6a_out/level_L3.vtu",
            "docs/audits/2026-09-28-batch7h-e6a-mesh-family/data/remote_run_36388479824/outputs/e6a_out/level_L3.npz",
            "docs/audits/2026-09-28-batch7h-e6a-mesh-family/data/remote_run_36388479824/outputs/e6a_out/level_L4.vtu",
            "docs/audits/2026-09-28-batch7h-e6a-mesh-family/data/remote_run_36388479824/outputs/e6a_out/level_L4.npz",
            "docs/audits/2026-09-28-batch7h-e6a-mesh-family/data/remote_run_36388479824/outputs/e6a_out/level_L5.vtu",
            "docs/audits/2026-09-28-batch7h-e6a-mesh-family/data/remote_run_36388479824/outputs/e6a_out/level_L5.npz",
            "docs/audits/2026-09-28-batch7h-e6b-poisson-junction-refinement/data/remote_run_36527372624/outputs/e6b_out/level_L3_state_P.npz",
            "docs/audits/2026-09-28-batch7h-e6b-poisson-junction-refinement/data/remote_run_36527372624/outputs/e6b_out/level_L4_state_P.npz",
            "docs/audits/2026-09-28-batch7h-e6b-poisson-junction-refinement/data/remote_run_36527372624/outputs/e6b_out/level_L5_state_P.npz",
            "docs/audits/2026-09-24-batch7h-e1-production-step-junction-equivalence/scripts/common_e1.py",
            "tcad/device/devsim/mesh_import.py",
            "tcad/device/devsim/semiconductor_equation.py",
            "tcad/mesh/viennaps_adapter.py",
        ],
        "outputs": [{"glob": "e6c_out/**/*.json", "max_mb": 50}, {"glob": "e6c_out/**/*.npz", "max_mb": 80}],
        "regenerate": "Rerun the profile. Every run is imported fresh in its own process; E6A / E6B inputs are hash-gated.",
    },
    "e6d_noncore_refinement": {
        "description": "Batch 7H-E6D: E6A L5 core held fixed, non-core refinement (production refine_mesh_near, seed |x| >= X02, 1 and 2 passes), pre-solve gates, then 0 V Poisson P/Q per valid mesh, one devsim.solve per process, at most 4 solves.",
        "entry": "docs/audits/2026-09-29-batch7h-e6d-noncore-refinement/scripts/run_e6d.py",
        "args": [],
        "params": {},
        "timeout_s": 9000,
        "inputs": [
            "docs/audits/2026-09-29-batch7h-e6d-noncore-refinement/PLAN.md",
            "docs/audits/2026-09-29-batch7h-e6d-noncore-refinement/PLAN.sha256",
            "docs/audits/2026-09-29-batch7h-e6d-noncore-refinement/scripts/run_e6d.py",
            "docs/audits/2026-09-29-batch7h-e6d-noncore-refinement/scripts/stage_e6d.py",
            "docs/audits/2026-09-29-batch7h-e6d-noncore-refinement/scripts/judge_e6d.py",
            "docs/audits/2026-09-29-batch7h-e6c-initialization-robustness/PLAN.md",
            "docs/audits/2026-09-29-batch7h-e6c-initialization-robustness/scripts/judge_e6c.py",
            "docs/audits/2026-09-29-batch7h-e6c-initialization-robustness/scripts/stage_e6c.py",
            "docs/audits/2026-09-29-batch7h-e6c-initialization-robustness/data/remote_run_36529279171/outputs/e6c_out/run_L5_P.json",
            "docs/audits/2026-09-29-batch7h-e6c-initialization-robustness/data/remote_run_36529279171/outputs/e6c_out/run_L5_Q.json",
            "docs/audits/2026-09-29-batch7h-e6c-initialization-robustness/data/remote_run_36529279171/outputs/e6c_out/run_L5_P_final.npz",
            "docs/audits/2026-09-29-batch7h-e6c-initialization-robustness/data/remote_run_36529279171/outputs/e6c_out/run_L5_Q_final.npz",
            "docs/audits/2026-09-29-batch7h-e6c-initialization-robustness/data/remote_run_36529279171/outputs/e6c_out/run_L4_P_final.npz",
            "docs/audits/2026-09-28-batch7h-e6b-poisson-junction-refinement/scripts/judge_e6b.py",
            "docs/audits/2026-09-28-batch7h-e6b-poisson-junction-refinement/data/remote_run_36527372624/outputs/e6b_out/level_L5_static.npz",
            "docs/audits/2026-09-28-batch7h-e6a-mesh-family/scripts/family_e6a.py",
            "docs/audits/2026-09-28-batch7h-e6a-mesh-family/data/remote_run_36388479824/outputs/e6a_out/level_L5.json",
            "docs/audits/2026-09-28-batch7h-e6a-mesh-family/data/remote_run_36388479824/outputs/e6a_out/level_L5.vtu",
            "docs/audits/2026-09-28-batch7h-e6a-mesh-family/data/remote_run_36388479824/outputs/e6a_out/level_L3.npz",
            "docs/audits/2026-09-28-batch7h-e6a-mesh-family/data/remote_run_36388479824/outputs/e6a_out/level_L4.npz",
            "docs/audits/2026-09-28-batch7h-e6a-mesh-family/data/remote_run_36388479824/outputs/e6a_out/level_L5.npz",
            "docs/audits/2026-09-25-batch7h-e2-nodevolume-first-bad-stage/scripts/stage_e2.py",
            "docs/audits/2026-09-25-batch7h-e2-nodevolume-first-bad-stage/scripts/trace_refine_e2.py",
            "docs/audits/2026-09-25-batch7h-e4-nonobtuse-quadtree-candidate/scripts/quadtree_e4.py",
            "docs/audits/2026-09-24-batch7h-e1-production-step-junction-equivalence/scripts/common_e1.py",
            "tcad/device/devsim/mesh_refine.py",
            "tcad/device/devsim/mesh_import.py",
            "tcad/device/devsim/semiconductor_equation.py",
            "tcad/mesh/viennaps_adapter.py",
        ],
        "outputs": [{"glob": "e6d_out/**/*.json", "max_mb": 20}, {"glob": "e6d_out/**/*.npz", "max_mb": 60},
                    {"glob": "e6d_out/**/*.vtu", "max_mb": 40}],
        "regenerate": "Rerun the profile. The refined meshes are rebuilt from the hash-gated E6A L5 mesh; every solve is a fresh import in its own process.",
    },
    "e6e_importer_repro": {
        "description": "Batch 7H-E6E step 1: unmodified production import_process_result() on the E6D G0/G1/G2 meshes (sha-gated), solve and DEVSIM write APIs trapped; records device returned or not and sum(NodeVolume) vs exact triangle area.",
        "entry": "docs/audits/2026-09-30-batch7h-e6e-area-conservation-gate/scripts/repro_e6e.py",
        "args": [],
        "params": {},
        "timeout_s": 3600,
        "inputs": [
            "docs/audits/2026-09-30-batch7h-e6e-area-conservation-gate/scripts/repro_e6e.py",
            "docs/audits/2026-09-28-batch7h-e6a-mesh-family/data/remote_run_36388479824/outputs/e6a_out/level_L5.vtu",
            "docs/audits/2026-09-29-batch7h-e6d-noncore-refinement/data/remote_run_36538742843/outputs/e6d_out/mesh_G1.vtu",
            "docs/audits/2026-09-29-batch7h-e6d-noncore-refinement/data/remote_run_36538742843/outputs/e6d_out/mesh_G2.vtu",
            "docs/audits/2026-09-24-batch7h-e1-production-step-junction-equivalence/scripts/common_e1.py",
            "tcad/device/devsim/mesh_import.py",
            "tcad/mesh/viennaps_adapter.py",
        ],
        "outputs": [{"glob": "e6e_repro_out/**/*.json", "max_mb": 5}],
        "regenerate": "Rerun the profile; inputs are sha-gated raw E6A/E6D meshes.",
    },
    "e6e_targeted": {
        "description": "Batch 7H-E6E targeted tests of the importer area-conservation gate (pure unit test + real DEVSIM / GUI / CLI test).",
        "entry": "docs/audits/2026-09-30-batch7h-e6e-area-conservation-gate/scripts/run_tests_e6e.py",
        "args": ["targeted"],
        "params": {},
        "timeout_s": 5400,
        "inputs": [
            "docs/audits/2026-09-30-batch7h-e6e-area-conservation-gate/PLAN.md",
            "docs/audits/2026-09-30-batch7h-e6e-area-conservation-gate/scripts/run_tests_e6e.py",
            "tcad/device/devsim/mesh_conservation.py",
            "tcad/device/devsim/mesh_import.py",
            "tcad_2d_stagewise.py",
            "tcad/cli/run_pipeline.py",
            "tests/unit/test_mesh_area_conservation_mock.py",
            "tests/integration/test_mesh_area_conservation_gate_real.py",
        ],
        "outputs": [{"glob": "e6e_targeted_out/**/*", "max_mb": 20}],
        "regenerate": "Rerun the profile.",
    },
    "e6e_full_regression": {
        "description": "Batch 7H-E6E: tests/run_regression.py exactly once after the targeted checks.",
        "entry": "docs/audits/2026-09-30-batch7h-e6e-area-conservation-gate/scripts/run_tests_e6e.py",
        "args": ["regression"],
        "params": {},
        "timeout_s": 20000,
        "inputs": [
            "docs/audits/2026-09-30-batch7h-e6e-area-conservation-gate/scripts/run_tests_e6e.py",
            "tests/run_regression.py",
            "tcad/device/devsim/mesh_conservation.py",
            "tcad/device/devsim/mesh_import.py",
        ],
        "outputs": [{"glob": "e6e_regression_out/**/*", "max_mb": 40}],
        "regenerate": "Rerun the profile.",
    },
    "e6e_r1_gate_uncertainty": {
        "description": "Batch 7H-E6E-R1: certification-uncertainty limit tests, E6E targeted test, small Laplace control, import-only diagnosis of two ViennaPS meshes (A: phase5 etch, B: implant-windows refinement).",
        "entry": "docs/audits/2026-09-30-batch7h-e6e-r1-gate-uncertainty/scripts/run_r1.py",
        "args": [],
        "params": {},
        "timeout_s": 5400,
        "inputs": [
            "docs/audits/2026-09-30-batch7h-e6e-r1-gate-uncertainty/PLAN.md",
            "docs/audits/2026-09-30-batch7h-e6e-r1-gate-uncertainty/scripts/run_r1.py",
            "docs/audits/2026-09-30-batch7h-e6e-r1-gate-uncertainty/scripts/diag_r1.py",
            "tcad/device/devsim/mesh_conservation.py",
            "tcad/device/devsim/mesh_import.py",
            "tests/unit/test_mesh_area_conservation_mock.py",
            "tests/integration/test_mesh_area_conservation_gate_real.py",
            "tests/integration/test_mesh_gate_small_laplace_control_real.py",
        ],
        "outputs": [{"glob": "e6e_r1_out/**/*", "max_mb": 30}],
        "regenerate": "Rerun the profile; meshes A and B are regenerated by their production calls.",
    },
    "e6f_blue_size_check": {
        "description": "Batch 7H-E6F: one pure-geometry size check of the blue refinement candidate (audit module) at the GUI default scale (E6A wafer_volume, 1e20 implant windows); 400000-triangle cap checked before allocation; no DEVSIM.",
        "entry": "docs/audits/2026-10-01-batch7h-e6f-quality-closure/scripts/big_blue_e6f.py",
        "args": [],
        "params": {},
        "timeout_s": 600,
        "inputs": [
            "docs/audits/2026-10-01-batch7h-e6f-quality-closure/scripts/big_blue_e6f.py",
            "docs/audits/2026-10-01-batch7h-e6f-quality-closure/scripts/refine_blue.py",
            "docs/audits/2026-10-01-batch7h-e6f-quality-closure/scripts/refine_old.py",
            "docs/audits/2026-09-28-batch7h-e6a-mesh-family/data/remote_run_36388479824/outputs/e6a_out/wafer_volume.vtu",
            "tcad/device/devsim/mesh_import.py",
            "tcad/physics/doping.py",
        ],
        "outputs": [{"glob": "e6f_big_out/**/*.json", "max_mb": 5}],
        "regenerate": "Rerun the profile.",
    },
    "e6g_structured_template": {
        "description": "Batch 7H-E6G: structured-grid transition-template remeshing -- unit tests, real B (GUI refinement path) and GUI-default 1e20 wafer through the production caller + importer area gate, Laplace and manufactured Poisson controls.",
        "entry": "docs/audits/2026-10-01-batch7h-e6g-structured-template/scripts/run_e6g.py",
        "args": [],
        "params": {},
        "timeout_s": 3600,
        "inputs": [
            "docs/audits/2026-10-01-batch7h-e6g-structured-template/CRITERIA.md",
            "docs/audits/2026-10-01-batch7h-e6g-structured-template/scripts/run_e6g.py",
            "docs/audits/2026-10-01-batch7h-e6g-structured-template/scripts/real_e6g.py",
            "docs/audits/2026-10-01-batch7h-e6g-structured-template/scripts/eval_e6g.py",
            "tcad/device/devsim/mesh_refine.py",
            "tcad/device/devsim/mesh_import.py",
            "tests/unit/test_mesh_structured_remesh_mock.py",
            "tests/integration/test_mesh_gate_manufactured_poisson_real.py",
            "docs/audits/2026-09-28-batch7h-e6a-mesh-family/data/remote_run_36388479824/outputs/e6a_out/wafer_volume.vtu",
        ],
        "outputs": [{"glob": "e6g_out/**/*", "max_mb": 40}],
        "regenerate": "Rerun the profile.",
    },
    "e6h_conformity_poisson": {
        "description": "Batch 7H-E6H: unit tests, exact conformity of the committed E6G B/F outputs, Poisson and linear controls on structured_lateral_refine transition meshes (real DEVSIM, small meshes).",
        "entry": "docs/audits/2026-10-01-batch7h-e6h-conformity-poisson/scripts/run_e6h.py",
        "args": [],
        "params": {},
        "timeout_s": 3600,
        "inputs": [
            "docs/audits/2026-10-01-batch7h-e6h-conformity-poisson/CRITERIA.md",
            "docs/audits/2026-10-01-batch7h-e6h-conformity-poisson/CRITERIA_ERRATUM_1.md",
            "docs/audits/2026-10-01-batch7h-e6h-conformity-poisson/scripts/run_e6h.py",
            "docs/audits/2026-10-01-batch7h-e6h-conformity-poisson/scripts/conformity_e6h.py",
            "docs/audits/2026-10-01-batch7h-e6h-conformity-poisson/scripts/conformity_bf.py",
            "docs/audits/2026-10-01-batch7h-e6h-conformity-poisson/scripts/op_analysis.py",
            "tcad/device/devsim/mesh_refine.py",
            "tcad/device/devsim/mesh_import.py",
            "tests/unit/test_mesh_structured_remesh_mock.py",
            "tests/unit/test_mesh_conformity_check_mock.py",
            "tests/unit/test_mesh_implant_refine_fallback_mock.py",
            "tests/integration/test_mesh_gate_poisson_transition_real.py",
        ],
        "outputs": [{"glob": "e6h_out/**/*", "max_mb": 20}],
        "regenerate": "Rerun the profile.",
    },
    "e6i_uniform_resistor_dd": {
        "description": "Batch 7H-E6I: low-field drift-diffusion current of a uniformly doped ACTIVE Si resistor on E6H transition meshes through the production path, plus GUI connection and UNSUPPORTED controls.",
        "entry": "docs/audits/2026-10-01-batch7h-e6i-uniform-resistor-dd/scripts/run_e6i.py",
        "args": [],
        "params": {},
        "timeout_s": 3600,
        "inputs": [
            "docs/audits/2026-10-01-batch7h-e6i-uniform-resistor-dd/CRITERIA.md",
            "docs/audits/2026-10-01-batch7h-e6i-uniform-resistor-dd/scripts/run_e6i.py",
            "docs/audits/2026-10-01-batch7h-e6i-uniform-resistor-dd/scripts/resistor_judge.py",
            "tests/unit/test_resistor_dd_judge_mock.py",
            "tests/integration/test_uniform_resistor_dd_current_real.py",
            "tests/integration/test_mesh_gate_poisson_transition_real.py",
            "tcad/device/devsim/semiconductor_equation.py",
            "tcad/device/devsim/doping_mapping.py",
            "tcad/characterization/pn_junction_iv_sweep.py",
        ],
        "outputs": [{"glob": "e6i_out/**/*", "max_mb": 20}],
        "regenerate": "Rerun the profile.",
    },
    "e6j_current_unit_contract": {
        "description": "Batch 7H-E6J: 2D DD current unit contract (A/cm, machine-readable metadata) -- mock test and one representative GUI measurement (E6I one_sided n=8, +1 mV) with CHEMICAL / UNKNOWN controls.",
        "entry": "docs/audits/2026-10-01-batch7h-e6j-current-unit-and-pn-plan/scripts/run_e6j.py",
        "args": [],
        "params": {},
        "timeout_s": 1800,
        "inputs": [
            "docs/audits/2026-10-01-batch7h-e6j-current-unit-and-pn-plan/CRITERIA.md",
            "docs/audits/2026-10-01-batch7h-e6j-current-unit-and-pn-plan/scripts/run_e6j.py",
            "tests/unit/test_current_unit_contract_mock.py",
            "tests/integration/test_gui_current_unit_contract_real.py",
            "tests/integration/test_uniform_resistor_dd_current_real.py",
            "tcad/characterization/interface.py",
            "tcad/characterization/io.py",
            "tcad/characterization/plotting.py",
            "tcad/characterization/pn_junction_iv_sweep.py",
            "tcad/characterization/robust_iv_sweep.py",
        ],
        "outputs": [{"glob": "e6j_out/**/*", "max_mb": 10}],
        "regenerate": "Rerun the profile.",
    },
    "e7a_official_material_extraction": {
        "description": "E7A: official ViennaPS 4.6.2 getMaterialLevelSet / saveVolumeMesh / getSurfaceMesh vs the project's save_locos_volume_mesh on explicit Si/SiO2, thin pad oxide and partial-mask LOCOS stacks (probe only, no production change).",
        "entry": "docs/audits/2026-10-01-e7a-official-material-extraction/scripts/run_e7a.py",
        "args": [],
        "params": {},
        "timeout_s": 3000,
        "inputs": [
            "docs/audits/2026-10-01-e7a-official-material-extraction/CRITERIA.md",
            "docs/audits/2026-10-01-e7a-official-material-extraction/scripts/run_e7a.py",
            "docs/audits/2026-10-01-e7a-official-material-extraction/scripts/probe_e7a.py",
            "tcad/backends/viennaps/io.py",
            "tcad/process/oxidation/locos.py",
            "tests/integration/_explicit_oxide_fixture.py",
        ],
        "outputs": [{"glob": "e7a_out/**/*", "max_mb": 60}],
        "regenerate": "Rerun the profile.",
    },
    "e7a_official_material_extraction_s1": {
        "description": "E7A supplement S1 (post hoc, see S1_CRITERIA.md): official saveVolumeMesh on a floored copy (R4) and per-material getMaterialLevelSet meshing diagnostics (R5). Probe only.",
        "entry": "docs/audits/2026-10-01-e7a-official-material-extraction/scripts/run_e7a.py",
        "args": ["--s1"],
        "params": {},
        "timeout_s": 1800,
        "inputs": [
            "docs/audits/2026-10-01-e7a-official-material-extraction/S1_CRITERIA.md",
            "docs/audits/2026-10-01-e7a-official-material-extraction/scripts/run_e7a.py",
            "docs/audits/2026-10-01-e7a-official-material-extraction/scripts/probe_e7a.py",
            "docs/audits/2026-10-01-e7a-official-material-extraction/scripts/probe_e7a_s1.py",
            "tcad/backends/viennaps/io.py",
            "tcad/process/oxidation/locos.py",
            "tests/integration/_explicit_oxide_fixture.py",
        ],
        "outputs": [{"glob": "e7a_out/**/*", "max_mb": 60}],
        "regenerate": "Rerun the profile.",
    },
    "e7a_official_material_extraction_s1b": {
        "description": "E7A supplement S1b (post hoc): B2 getMaterialLevelSet(SiO2) empty-surface recording and a pad-thickness scan at grid 0.10. Probe only.",
        "entry": "docs/audits/2026-10-01-e7a-official-material-extraction/scripts/run_e7a.py",
        "args": ["--s1b"],
        "params": {},
        "timeout_s": 900,
        "inputs": [
            "docs/audits/2026-10-01-e7a-official-material-extraction/S1_CRITERIA.md",
            "docs/audits/2026-10-01-e7a-official-material-extraction/scripts/run_e7a.py",
            "docs/audits/2026-10-01-e7a-official-material-extraction/scripts/probe_e7a.py",
            "docs/audits/2026-10-01-e7a-official-material-extraction/scripts/probe_e7a_s1.py",
            "tcad/backends/viennaps/io.py",
        ],
        "outputs": [{"glob": "e7a_out/**/*", "max_mb": 20}],
        "regenerate": "Rerun the profile.",
    },
    "e7a_official_material_extraction_s1c": {
        "description": "E7A supplement S1c (post hoc): thin-slab RELATIVE_COMPLEMENT on never-unioned planes vs the wrapped getMaterialLevelSet. Probe only.",
        "entry": "docs/audits/2026-10-01-e7a-official-material-extraction/scripts/run_e7a.py",
        "args": ["--s1b", "--s1c"],
        "params": {},
        "timeout_s": 600,
        "inputs": [
            "docs/audits/2026-10-01-e7a-official-material-extraction/S1_CRITERIA.md",
            "docs/audits/2026-10-01-e7a-official-material-extraction/scripts/run_e7a.py",
            "docs/audits/2026-10-01-e7a-official-material-extraction/scripts/probe_e7a.py",
            "docs/audits/2026-10-01-e7a-official-material-extraction/scripts/probe_e7a_s1.py",
        ],
        "outputs": [{"glob": "e7a_out/**/*", "max_mb": 10}],
        "regenerate": "Rerun the profile.",
    },
    "e6k_pn_1d_diagnostic": {
        "description": "E6K: first production-path 1D symmetric p-n diode diagnostic (1D resistor unit control + 3 meshes forward/reverse, <= 45 solves) with analytic reference comparison; six separate verdicts, no PN validation claim.",
        "entry": "docs/audits/2026-10-01-e6k-pn-1d-diagnostic/scripts/run_e6k.py",
        "args": [],
        "params": {},
        "timeout_s": 1800,
        "inputs": [
            "docs/audits/2026-10-01-e6k-pn-1d-diagnostic/PN_PLAN_v2.md",
            "docs/audits/2026-10-01-e6k-pn-1d-diagnostic/scripts/run_e6k.py",
            "docs/audits/2026-10-01-e6k-pn-1d-diagnostic/scripts/pn_reference.py",
            "docs/audits/2026-10-01-e6k-pn-1d-diagnostic/scripts/judge_e6k.py",
            "tests/integration/test_pn_1d_diagnostic_real.py",
            "tests/unit/test_pn_reference_mock.py",
            "tests/unit/test_pn_judge_mock.py",
            "tests/unit/test_current_unit_contract_mock.py",
            "tcad/characterization/interface.py",
            "tcad/characterization/pn_junction_iv_sweep.py",
            "docs/audits/2026-10-01-batch7h-e6j-current-unit-and-pn-plan/data/remote_run_36759423132/remote-run-24/outputs/e6j_out/gui_unit_contract.json",
        ],
        "outputs": [{"glob": "e6k_out/**/*", "max_mb": 30}],
        "regenerate": "Rerun the profile.",
    },
    "e6m_pn_2d_1d_consistency": {
        "description": "E6M: limited 2D-1D consistency of the E6K p-n problem (audit path; the production 2D step-junction gate is recorded as refusing); 3 meshes x forward/reverse, 42 solves planned; separate verdicts, no PN validation claim.",
        "entry": "docs/audits/2026-10-02-e6m-pn-2d-1d-consistency/scripts/run_e6m.py",
        "args": [],
        "params": {},
        "timeout_s": 1800,
        "inputs": [
            "docs/audits/2026-10-02-e6m-pn-2d-1d-consistency/PLAN.md",
            "docs/audits/2026-10-02-e6m-pn-2d-1d-consistency/scripts/run_e6m.py",
            "docs/audits/2026-10-02-e6m-pn-2d-1d-consistency/scripts/e6m_metrics.py",
            "docs/audits/2026-10-02-e6m-pn-2d-1d-consistency/scripts/judge_e6m.py",
            "tests/integration/test_pn_2d_1d_consistency_real.py",
            "tests/unit/test_e6m_judge_mock.py",
            "tests/unit/test_e6l_correction_mock.py",
            "docs/audits/2026-10-01-e6k-pn-1d-diagnostic/data/remote_run_36815925901/remote-run-31/outputs/e6k_out/pn_1d_diagnostic.json",
            "docs/audits/2026-10-01-e6k-pn-1d-diagnostic/data/remote_run_36815925901/remote-run-31/outputs/e6k_out/states.npz",
            "tcad/characterization/pn_junction_iv_sweep.py",
            "tcad/device/devsim/doping_mapping.py",
            "tcad/device/devsim/mesh_import.py",
        ],
        "outputs": [{"glob": "e6m_out/**/*", "max_mb": 60}],
        "regenerate": "Rerun the profile.",
    },
}

# Global limits (bytes / counts). Anything over budget is omitted and reported, never silently dropped.
MAX_TOTAL_OUTPUT_MB = 200
MAX_LOG_MB = 20
REQUEST_ID_PATTERN = r"^[A-Za-z0-9._-]{1,64}$"
