#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Bosch DRIE — one Etching implementation among several.

Physics-based cyclic passivation / bottom-breakthrough / silicon-etch
process built from ViennaPS's SingleParticleProcess and
MultiParticleProcess primitives (see tcad/backends/viennaps/session.py).

Moved here (Phase 2) from tcad/backends/viennaps/bosch.py, its Phase-1
temporary home. The algorithm is byte-for-byte the same as the version
that passed tests/test_phase1_bosch_mock.py; only its location and the
fact that it now implements ProcessStep + registers itself changed.

Real API used here (verified against installed ViennaPS 4.6.2 via
`vps.SingleParticleProcess.__init__.__doc__` /
`vps.MultiParticleProcess.__init__.__doc__`, and already exercised in
Phase 1):
    vps.SingleParticleProcess(rate, stickingProbability, sourceExponent,
                               maskMaterial=...)
    vps.MultiParticleProcess().addNeutralParticle(stickingProbability)
    vps.MultiParticleProcess().addIonParticle(sourcePower, thetaRMin=...)
    vps.MultiParticleProcess().setRateFunction(fn)
    vps.Process(domain, model, duration).apply()
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict

from tcad.backends.viennaps import session
from tcad.backends.viennaps.io import DEFAULT_FLOOR_DEPTH_UM, SnapshotRecorder, save_volume_mesh
from tcad.process.base import ProcessStep
from tcad.process.registry import register


@register
class BoschDRIEEtch(ProcessStep):
    category = "etching"
    name = "bosch_drie"
    display_name = "Bosch DRIE (physics-based, cyclic)"

    def run(self, recipe: Dict[str, Any], output_dir: str) -> Dict[str, Any]:
        """
        Actual ViennaPS geometry evolution.

        The geometry is not generated by a fake scallop formula.

        Sequence:
            MakeTrench
            initial etch
            polymer deposition
            polymer breakthrough
            silicon etch
            remove polymer
            repeat
        """

        module = session.require_viennaps()

        # Fresh wafer normally; the previous step's domain when this
        # step is part of a process flow (see ProcessStep.prepare_domain).
        geometry = self.prepare_domain(recipe)

        # Which material tag actually blocks etching here. Was hardcoded
        # to module.Material.Mask -- correct for a FRESH wafer, where
        # prepare_domain()'s own MakeTrench path always tags its mask
        # "Mask". Wrong for a CHAINED step (prepare_domain() ->
        # remask_domain()), where the GUI deliberately tags a real
        # lithography resist "PHS" (tcad_2d_stagewise.py's own
        # _RESIST_MATERIAL, kept distinct from ViennaPS's native "Mask"
        # so photoresist can be told apart from a hard mask). With the
        # hardcode, a real oxidation -> lithography -> Bosch DRIE chain
        # silently ignored the resist entirely -- etch_rate() below never
        # matched "PHS" against Material.Mask, so the masked region
        # etched exactly like open silicon, with no error or warning.
        # Confirmed a real, physical masking effect belongs here at all:
        # Osipov et al., "Influence of operation parameters on
        # BOSCH-process technological characteristics", Materials Today:
        # Proceedings (2020) -- measured Si/photoresist etch selectivity
        # around 38:1 (SF6/CHF3 chemistry, ICP reactor) for exactly this
        # process. ViennaPS's own maskMaterial is a binary gate (0 or the
        # full rate), not that finite ratio -- a known simplification
        # already implicit in every other model here (isotropic.py,
        # directional.py) that reads mask_material the same dynamic way;
        # this fix brings bosch_drie.py in line with that same existing,
        # already-verified convention, not a new physics model.
        mask_material = getattr(module.Material, recipe.get("mask_material", "Mask"))

        # --------------------------------------------------------
        # Passivation
        # --------------------------------------------------------

        polymer_deposition = module.SingleParticleProcess(
            rate=recipe["polymer_rate"],
            stickingProbability=recipe["polymer_sticking"],
        )

        # --------------------------------------------------------
        # Bottom polymer breakthrough
        # --------------------------------------------------------

        polymer_breakthrough = module.SingleParticleProcess(
            rate=-recipe["polymer_rate"],
            stickingProbability=1.0,
            sourceExponent=recipe["ion_source_exponent"],
            maskMaterial=mask_material,
        )

        # --------------------------------------------------------
        # Silicon etch
        # --------------------------------------------------------

        silicon_etch = module.MultiParticleProcess()

        silicon_etch.addNeutralParticle(
            recipe["neutral_sticking"]
        )

        silicon_etch.addIonParticle(
            sourcePower=recipe["ion_source_exponent"],
            thetaRMin=60.0,
        )

        def etch_rate(fluxes, material):
            if material == mask_material:
                return 0.0

            rate = fluxes[1] * recipe["ion_rate"]

            if material == module.Material.Si:
                rate += fluxes[0] * recipe["neutral_rate"]

            return rate

        silicon_etch.setRateFunction(etch_rate)

        recorder = SnapshotRecorder(output_dir)
        recorder.capture(geometry, "000_initial")

        # Initial silicon etch
        module.Process(
            geometry,
            silicon_etch,
            recipe["etch_time_s"],
        ).apply()

        recorder.capture(geometry, "001_initial_etch")

        # --------------------------------------------------------
        # Bosch cycles
        # --------------------------------------------------------

        for cycle in range(1, recipe["cycles"] + 1):

            # 1. polymer passivation
            geometry.duplicateTopLevelSet(
                module.Material.Polymer
            )

            module.Process(
                geometry,
                polymer_deposition,
                1.0,
            ).apply()

            recorder.capture(geometry, f"{cycle:03d}_passivation")

            # 2. bottom breakthrough
            module.Process(
                geometry,
                polymer_breakthrough,
                1.0,
            ).apply()

            recorder.capture(geometry, f"{cycle:03d}_breakthrough")

            # 3. silicon etch
            module.Process(
                geometry,
                silicon_etch,
                recipe["etch_time_s"],
            ).apply()

            recorder.capture(geometry, f"{cycle:03d}_silicon_etch")

            # 4. remove polymer before next cycle
            geometry.removeTopLevelSet()
            geometry.removeStrayPoints()

            recorder.capture(geometry, f"{cycle:03d}_cycle_end")

        final_mesh = Path(output_dir) / "bosch_final"

        final_mesh_path = save_volume_mesh(
            geometry, final_mesh,
            floor_depth_um=recipe.get("silicon_depth_um", DEFAULT_FLOOR_DEPTH_UM),
        )

        return {
            "final_mesh": final_mesh_path,
            "snapshots": recorder.snapshots,
            "cycles": recipe["cycles"],
        }


def run_viennaps_bosch(recipe: Dict[str, Any], output_dir: str) -> Dict[str, Any]:
    """Backward-compatible function form (used by tcad_2d_stagewise.py).

    Equivalent to registry.get("etching", "bosch_drie")().run(recipe, output_dir).
    """
    return BoschDRIEEtch().run(recipe, output_dir)
